server:
  port: 8081
database:
  driver: postgres
  host: localhost
  port: 5432
  dbname: mg
env: "local"
access_secret: test-code
issuer: hangover
seed_path: "/Users/jai/Documents/Projects/UK/gin-starter/seeds/"